### ISSUE TITLE
Eve Motion (or Room) won't pair on RPi3

### ISSUE THREAD

**Issue by sotomski** [mozilla-iot/homekit-adapter#36] opened 2019-09-07 19:37 UTC
Hi,

I've been trying to pair my Eve Room and Motion devices and I constantly get the "Incorrect PIN" error. I've looked into adapter's source code and made sure that I'm typing the pin in a correct format. 
I get the error 100% of the time, unlike in this case: https://github.com/mozilla-iot/homekit-adapter/issues/30

Any help would be very appreciated. The ability to use Mozilla technology for HomeKit devices would be a godsend! 

Thanks,
Karol

Also, here are the logs I got from the device:
```
2019-09-07 20:26:21.493 INFO   : Loading add-on: homekit-adapter
2019-09-07 20:26:22.268 INFO   : homekit: Opening database: /home/pi/.mozilla-iot/config/db.sqlite3
2019-09-07 20:26:22.316 INFO   : homekit: Loading add-on for homekit-adapter from /home/pi/.mozilla-iot/addons/homekit-adapter
2019-09-07 20:26:24.544 INFO   : homekit: Found IP device: { name: 'Philips hue - 4AFA59',
2019-09-07 20:26:24.547 INFO   : homekit:   address: '192.168.0.100',
2019-09-07 20:26:24.551 INFO   : homekit:   port: 8080,
2019-09-07 20:26:24.553 INFO   : homekit:   'c#': 33,
2019-09-07 20:26:24.556 INFO   : homekit:   ff: 1,
2019-09-07 20:26:24.558 INFO   : homekit:   id: 'D4:C8:13:DD:EA:F5',
2019-09-07 20:26:24.560 INFO   : homekit:   md: 'BSB002',
2019-09-07 20:26:24.562 INFO   : homekit:   pv: '1.1',
2019-09-07 20:26:24.565 INFO   : homekit:   's#': 1,
2019-09-07 20:26:24.567 INFO   : homekit:   sf: 0,
2019-09-07 20:26:24.569 INFO   : homekit:   ci: 2 }
2019-09-07 20:26:24.572 INFO   : homekit: Error loading device D4:C8:13:DD:EA:F5: Key not found
2019-09-07 20:26:24.573 INFO   : homekit: Found BLE device: { CoID: 76,
2019-09-07 20:26:24.575 INFO   : homekit:   TY: 6,
2019-09-07 20:26:24.577 INFO   : homekit:   AIL: 109,
2019-09-07 20:26:24.578 INFO   : homekit:   SF: 0,
2019-09-07 20:26:24.580 INFO   : homekit:   DeviceID: '34:04:e0:ac:9d:30',
2019-09-07 20:26:24.581 INFO   : homekit:   ACID: 7,
2019-09-07 20:26:24.583 INFO   : homekit:   GSN: 122,
2019-09-07 20:26:24.584 INFO   : homekit:   CN: 1,
2019-09-07 20:26:24.585 INFO   : homekit:   CV: 2 }
2019-09-07 20:26:24.587 INFO   : homekit: Error loading device 34:04:e0:ac:9d:30: Key not found
2019-09-07 20:26:24.986 INFO   : homekit: Found BLE device: { CoID: 76,
2019-09-07 20:26:24.988 INFO   : homekit:   TY: 6,
2019-09-07 20:26:24.990 INFO   : homekit:   AIL: 205,
2019-09-07 20:26:24.991 INFO   : homekit:   SF: 0,
2019-09-07 20:26:24.993 INFO   : homekit:   DeviceID: '28:17:e6:da:fc:c7',
2019-09-07 20:26:24.994 INFO   : homekit:   ACID: 10,
2019-09-07 20:26:24.995 INFO   : homekit:   GSN: 3,
2019-09-07 20:26:24.997 INFO   : homekit:   CN: 2,
2019-09-07 20:26:24.998 INFO   : homekit:   CV: 2 }
2019-09-07 20:26:25.001 INFO   : homekit: Error loading device 28:17:e6:da:fc:c7: Key not found
2019-09-07 20:26:26.920 INFO   : homekit: Found BLE device: { CoID: 76,
2019-09-07 20:26:26.923 INFO   : homekit:   TY: 6,
2019-09-07 20:26:26.924 INFO   : homekit:   AIL: 49,
2019-09-07 20:26:26.926 INFO   : homekit:   SF: 1,
2019-09-07 20:26:26.927 INFO   : homekit:   DeviceID: '72:45:ab:85:02:49',
2019-09-07 20:26:26.929 INFO   : homekit:   ACID: 10,
2019-09-07 20:26:26.931 INFO   : homekit:   GSN: 2,
2019-09-07 20:26:26.932 INFO   : homekit:   CN: 4,
2019-09-07 20:26:26.934 INFO   : homekit:   CV: 2 }
2019-09-07 20:26:26.936 INFO   : homekit: Error loading device 72:45:ab:85:02:49: Key not found
2019-09-07 20:26:28.807 INFO   : About to call startPairing on HomeKitAdapter
2019-09-07 20:26:28.845 INFO   : Opened a new things socket
2019-09-07 20:26:28.849 INFO   : homekit: Adapter: HomeKitAdapter id homekit-adapter pairing started
2019-09-07 20:26:32.982 INFO   : homekit: Found BLE device: { CoID: 76,
2019-09-07 20:26:32.984 INFO   : homekit:   TY: 6,
2019-09-07 20:26:32.986 INFO   : homekit:   AIL: 205,
2019-09-07 20:26:32.987 INFO   : homekit:   SF: 0,
2019-09-07 20:26:32.989 INFO   : homekit:   DeviceID: '97:bb:64:d2:bb:1b',
2019-09-07 20:26:32.990 INFO   : homekit:   ACID: 10,
2019-09-07 20:26:32.991 INFO   : homekit:   GSN: 120,
2019-09-07 20:26:32.993 INFO   : homekit:   CN: 2,
2019-09-07 20:26:32.994 INFO   : homekit:   CV: 2 }
2019-09-07 20:26:32.996 INFO   : homekit: Error loading device 97:bb:64:d2:bb:1b: Key not found
2019-09-07 20:26:42.922 INFO   : AdapterProxy: setPin: 478-80-431 for: homekit-72:45:ab:85:02:49
2019-09-07 20:27:05.443 INFO   : homekit: Pairing failed for device 72:45:ab:85:02:49: Timeout
2019-09-07 20:27:05.446 ERROR  : homekit: AddonManagerProxy: Failed to set PIN for device homekit-72:45:ab:85:02:49
2019-09-07 20:27:05.448 ERROR  : homekit: undefined
2019-09-07 20:27:05.450 ERROR  : Failed to set PIN for homekit-72:45:ab:85:02:49: undefined
```

**Comment by mrstegeman** [comment] 2019-09-09 17:10
You're getting a generic timeout error, so the best I can recommend is the following:
* Try moving the devices closer, if possible.
* If you have your RPi connected via ethernet, you can disable the Wi-Fi module, which should help Bluetooth performance dramatically. Instructions are in the [README](https://github.com/mozilla-iot/homekit-adapter/blob/master/README.md#troubleshooting).
* If you still can't get things to work, try restarting the Pi and/or the bluetooth service:
```systemctl restart bluetooth```

**Comment by mrstegeman** [comment] 2020-03-18 20:42
Duplicate of #30

**Closed by mrstegeman** 2020-03-18 20:42 UTC
